### ISSUE TITLE
Problems running snorky demos

### ISSUE THREAD

**Issue by Heroico** [ntrrgc/snorky#1]
Hi there!

I was trying out the **snorky_todo** demo, and after a few seconds, the snorky server becomes unresponsive. Something to do with Tornado.

```
INFO:tornado.access:200 POST /backend (127.0.0.1) 0.74ms
ERROR:tornado.application:Uncaught exception GET /ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5001', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Pragma': 'no-cache', 'Accept-Language': 'en-US,en;q=0.5', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive, Upgrade', 'Origin': 'http://0.0.0.0:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Host': 'localhost:5001', 'Upgrade': 'websocket', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0', 'Sec-Websocket-Extensions': 'permessage-deflate', 'Sec-Websocket-Key': 'lQ/+gcV1vwNqSbU+Tqxv0g==', 'Sec-Websocket-Version': '13'})
Traceback (most recent call last):
  File "/home/heroico/.pyenv/versions/3.4.1/lib/python3.4/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "/home/heroico/.pyenv/versions/3.4.1/lib/python3.4/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/heroico/.pyenv/versions/3.4.1/lib/python3.4/site-packages/snorky-0.1.0_a3-py3.4.egg/snorky/request_handlers/websocket.py", line 61, in its_ping_time
    self.ping('')
  File "/home/heroico/.pyenv/versions/3.4.1/lib/python3.4/site-packages/tornado/websocket.py", line 251, in ping
    self.ws_connection.write_ping(data)
  File "/home/heroico/.pyenv/versions/3.4.1/lib/python3.4/site-packages/tornado/websocket.py", line 679, in write_ping
    assert isinstance(data, bytes)
AssertionError
```

From what I can see, this happens because "data" is an empty **str** at the point of the assertion. Looks like a typical py3 vs py2 issue.

I am using python 3.4, installed from pyenv. I built snorky from the github repo using **python setup.py install**.

Is this expected to fail? Or should it be running?

**Comment by ntrrgc** [comment]
Hi, thanks for your time trying out Snorky.

Definitely this should not be happening. I'll check it out later more carefully but it looks like `self.ping('')` should be `self.ping(b'')`. You can try to change it for the meantime if you want.

Pings are packages sent periodically between client and server to avoid NAT routers forgetting about the websocket connections and therefore both getting disconnected without none of them even noticing.

**Comment by Heroico** [comment]
Yes, it worked as you suggested.

By the way, thank you for putting up snorky!
